<div class="container">
    <div class="row">
        <div class="col-md-8">
            <p class="faq_regular_font">We invite you to share your images and videos in this  library.  Uploading images is easy and will only take a few minutes of your time. We are accumulating images of  all cell types from all organisms, including intracellular structures and  movies or animations demonstrating functions.   This ambitious project obviously is multiyear and relies upon the cell  biology community to populate the library.   <em>The Cell Image Library™</em> aims to be as useful to the researcher and  the public as are the sequence databases for nucleic acids and proteins.  Toward that end, the images and videos will  be annotated by professionals with broad disciplinary expertise.  Raw data as well as data with limited  processing will be the most valuable.</p>
            <p>&nbsp;</p>
            <p class="faq_regular_font top-buffer">Please join us in this effort by allowing us to include your  image collections and videos in this open access library, <em>and</em> by sharing your raw data.  Our team of professional annotators will work  with your valuable data to assure its accuracy before presenting it to the  scientific and lay communities. Their annotations will provide useful information  about the images to allow researchers to explore data generated by biologists.</p>
            <p>&nbsp;</p>
            <p class="faq_regular_font top-buffer">If you wish to upload a very large number of images, or have trouble uploading, please e-mail David Orloff at <a href="mailto: dorloff@ncmir.ucsd.edu">dorloff@ncmir.ucsd.edu</a> for assistance.</p>
        </div>
        <div class="col-md-4">
            
        <span class="cil_title">Help Us Build The Library</span>
        <span class="cil_smaller_font">Interested in helping us build the Library? Download this flyer and post it in your lab and distribute to your colleagues.  Click the image below to view full size.</span>
        <center>
        <a href="/pages/assist">
        <img class="assist_small_img" src="/pix/assist_flyer.jpg">
        </a>
        </center>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <span class="cil_title">Uploading Your Images</span>
            <span class="faq_regular_font">Please e-mail David Orloff at <a href="mailto: dorloff@ncmir.ucsd.edu">dorloff@ncmir.ucsd.edu</a> for assistance</span>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-12">
            <span class="cil_title">Describing Your Images</span>
            <p class="faq_regular_font">To be searchable, each image will be entered into the library database with specific information that allows its identification during a user’s search. To aid in the annotation process, we ask that you supply us with as much information as you can about your images, including:</p>
            <p>&nbsp;</p>
            <ol class="participate_image_info">
            <li class="faq_regular_font">Biological Source (organism, cell type, cellular components, and fixation method, sectioning, etc. if applicable)</li>
            <li class="faq_regular_font">Biological Context and Probe (e.g., mitotic spindle during division labeled with tubulin primary antibody and Alexa 488 secondary or EGFP-tubulin)</li>
            <li class="faq_regular_font">Equipment used (e.g., microscope manufacturer, objective with NA, camera, confocal)</li>
            <li class="faq_regular_font">Acquisition parameters for time series (e.g., taken at 2 frames per second or confocal z stack taken with 1 Airy unit slices), post-processing of still images, if any</li>
            <li class="faq_regular_font">Magnification of image (either a scale bar or a note with microns/pixel)</li>
            </ol>
            <p class="faq_regular_font">Please include your contact information to allow the annotators to get in touch with you if they have any further questions about the image. This contact information will not be made public.</p>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-12">
            <span class="cil_title">Submitting Your Images</span>
            <p class="faq_regular_font">Please visit our <a href="/pages/license">Licensing Page</a> for more information on submitting both published and unpublished images.</p>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-12">
            <span class="cil_title">Citing The Library in Your Resume/CV</span>
            <p class="faq_regular_font">To cite original images, videos, and animations published in The Cell we suggest the following format:</p>
            <p>&nbsp;</p>
            <p class="faq_regular_font">Brandner, D. and Withers, G. (2010) Images of &lt;<em>description&nbsp;</em>&gt;.&nbsp;&nbsp;The Cell Image Library, <a href="/pages/contribute?href=www.cellimagelibrary.org">www.cellimagelibrary.org</a>, CIL numbers 10106, 10107, and 10108,&nbsp;ASCB.</p>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-12">
            <span class="cil_title">Survey</span>
            <p class="faq_regular_font">Please take this brief <a href="http://www.zoomerang.com/Survey/WEB22BSKGLKDZV" class="survey_plain" target="_blank">survey</a> to help us improve the upload experience. <a href="http://www.zoomerang.com/Survey/WEB22BSKGLKDZV" class="button survey" target="_blank">!</a></p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
        </div>
    </div>
    
</div>
